stages:
  - build
  - analyze
  - security

variables:
  SONARQUBE_URL: http://sonarqube:9000
  SONAR_TOKEN: $SONAR_TOKEN

image: python:3.9-slim

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - echo "Building application..."
    - python app.py --help  # Burada sadece basit bir test yapılıyor. Uygulamanızın sağlıklı çalıştığını doğrulamak için uygun bir komut kullanabilirsiniz.

analyze:
  stage: analyze
  image:
    name: sonarsource/sonar-scanner-cli
    entrypoint: [""]
  script:
    - sonar-scanner \
      -Dsonar.projectKey=myapp \
      -Dsonar.sources=. \
      -Dsonar.host.url=$SONARQUBE_URL \
      -Dsonar.login=$SONAR_TOKEN
  only:
    - main

security:
  stage: security
  image: aquasec/trivy:latest
  script:
    - trivy fs --format json --output trivy-report.json .
    - cat trivy-report.json
    - trivy fs --severity HIGH,CRITICAL --no-progress .
  only:
    - main
