stages:
  - build
  - analyze
  - security

variables:
  SONARQUBE_URL: http://sonarqube:9000
  SONAR_TOKEN: $SONAR_TOKEN
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:dind
    command: ["--host=tcp://0.0.0.0:2375", "--tls=false"]

image: docker:latest

build:
  stage: build
  script:
    - docker build -t myapp:latest .
    - docker tag myapp:latest $CI_REGISTRY/mygroup/myapp:$CI_COMMIT_SHA
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/mygroup/myapp:$CI_COMMIT_SHA

analyze:
  stage: analyze
  image:
    name: sonarsource/sonar-scanner-cli
    entrypoint: [""]
  script:
    - sonar-scanner \
      -Dsonar.projectKey=myapp \
      -Dsonar.sources=. \
      -Dsonar.host.url=$SONARQUBE_URL \
      -Dsonar.login=$SONAR_TOKEN
  only:
    - main

security:
  stage: security
  image: aquasec/trivy:latest
  script:
    - trivy image --format json --output trivy-report.json $CI_REGISTRY/mygroup/myapp:$CI_COMMIT_SHA
    - cat trivy-report.json
    - trivy image --severity HIGH,CRITICAL --no-progress $CI_REGISTRY/mygroup/myapp:$CI_COMMIT_SHA
  only:
    - main
